services:
  app:
    image: github.com/a10adotapp/brain-squeeze.a10a.app
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    container_name: brain-squeeze-a10a-app-app
    command: sleep infinity
    volumes:
      - ..:/home/vscode/brain-squeeze.a10a.app
    env_file:
      - .env
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/brain_squeeze_a10a_app_local"
      WEBHOOK_IMAGE_DOWNLOAD_DIRNAME: "/home/vscode/brain-squeeze.a10a.app/public/webhook"
    ports:
      - 3000:3000

  db:
    image: mysql:8
    container_name: brain-squeeze-a10a-app-db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_TCP_PORT: 3306
      MYSQL_DATABASE: "brain_squeeze_a10a_app_local"
    ports:
      - 3306:3306
